# Generated by Django 5.0.4 on 2024-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRuangan', models.CharField(max_length=200)),
                ('Tanggal_Pengajuan', models.DateTimeField(auto_now_add=True)),
                ('Tanggal_Penggunaan', models.DateTimeField(auto_now_add=True)),
                ('durasi', models.TimeField()),
            ],
        ),
    ]
