# Generated by Django 5.0.4 on 2024-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='Tanggal_Penggunaan',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='durasi',
            field=models.DurationField(),
        ),
    ]
