# Generated by Django 5.0.4 on 2024-05-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_reservasi_tanggal_penggunaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Kosong', max_length=20),
        ),
    ]
