# Generated by Django 5.0.4 on 2024-05-10 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_alter_reservasi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='Nama_Peminjam',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 8, 32, 57, 525879, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
