# Generated by Django 5.0.4 on 2024-05-13 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_reservasi_keterangan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasi',
            old_name='durasi',
            new_name='Waktu_Mulai',
        ),
        migrations.AddField(
            model_name='reservasi',
            name='Waktu_Selesai',
            field=models.DurationField(default=datetime.datetime(2024, 5, 13, 23, 59, 59, 435477, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
