# Generated by Django 5.0.4 on 2024-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0007_rename_durasi_reservasi_waktu_mulai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='Tanggal_Penggunaan',
            field=models.DateField(),
        ),
    ]
