# Generated by Django 5.0.4 on 2024-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0008_alter_reservasi_tanggal_penggunaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='Keterangan',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Belum diproses', max_length=20),
        ),
    ]
