# Generated by Django 5.0.4 on 2024-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_alter_reservasi_keterangan_alter_reservasi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='Waktu_Mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='Waktu_Selesai',
            field=models.TimeField(),
        ),
    ]
