# Generated by Django 5.0.4 on 2024-06-08 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_reservasi_email_reservasi_name_reservasi_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasi',
            old_name='Tanggal_Penggunaan',
            new_name='Tanggal_Penggunaan_Mulai',
        ),
        migrations.AddField(
            model_name='reservasi',
            name='Tanggal_Penggunaan_Selesai',
            field=models.DateField(default=datetime.datetime(2024, 6, 8, 17, 53, 2, 135104, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
