# Generated by Django 5.0.4 on 2024-06-09 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0012_rename_tanggal_penggunaan_reservasi_tanggal_penggunaan_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='NIM',
            field=models.CharField(default=datetime.datetime(2024, 6, 9, 5, 13, 41, 710879, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
