# Generated by Django 5.0.4 on 2024-04-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('IdRuangan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NamaRuangan', models.CharField(max_length=100)),
                ('Kapasitas', models.IntegerField()),
                ('Lokasi', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Kosong', max_length=20)),
            ],
        ),
    ]
