# Generated by Django 5.0.4 on 2024-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Kosong', max_length=20),
        ),
    ]
