# Generated by Django 5.0.4 on 2024-04-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
