# Generated by Django 5.0.4 on 2024-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_remove_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Kosong', max_length=20),
        ),
    ]
