# Generated by Django 5.0.4 on 2024-05-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
