# Generated by Django 5.0.4 on 2024-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_room_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Foto',
            field=models.ImageField(upload_to='Room/static/img'),
        ),
    ]
