# Generated by Django 5.0.4 on 2024-05-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_alter_room_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Foto',
            field=models.ImageField(upload_to='Room'),
        ),
    ]
