# Generated by Django 5.0.4 on 2024-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='status',
            field=models.CharField(choices=[('Kosong', 'Kosong'), ('Dalam proses', 'Dalam proses'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Kosong', max_length=20),
        ),
    ]
