# Generated by Django 5.0.4 on 2024-05-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jadwal', '0002_jadwal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='status',
        ),
    ]
